---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for install
  become: yes
  stat:
    path: '{{ starship_install_dir }}'
  changed_when: False
  register: starship_binary
- when: not starship_binary.stat.exists
  block:
    - name: download
      become: yes
      become_user: root
      get_url:
        url: '{{ starship_url }}'
        dest: /tmp/{{ starship_archive }}
        checksum: '{{ starship_checksum }}'
        mode: 0644
    - name: mkdir
      become: yes
      become_user: root
      file:
        path: '{{ starship_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ starship_archive }}
        dest: '{{ starship_install_dir }}'
        creates: '{{ starship_exe }}'
  always:
    - name: cleanup
      become: yes
      become_user: root
      file:
        path: /tmp/{{ starship_archive }}
        state: absent
- name: link
  become: yes
  become_user: root
  file:
    src: '{{ starship_exe }}'
    dest: '{{ starship_link }}'
    state: link
