- src: https://github.com/geerlingguy/ansible-role-docker
  name: geerlingguy.docker
  version: 3.1.1
- src: https://github.com/geerlingguy/ansible-role-pip
  name: geerlingguy.pip
  version: 2.0.0
- src: https://github.com/andrewrothstein/ansible-starship
  name: andrewrothstein.starship
  version: v1.0.13
- src: https://github.com/diodonfrost/ansible-role-terraform
  name: diodonfrost.terraform
  version: 1.6.0
- src: https://github.com/drew-kun/ansible-nerdfonts
  name: drew-kun.nerdfonts
- src: https://github.com/huxoll/ansible-role-azure-cli
  name: huxoll.azure-cli
  version: 1.1.1
- src: https://github.com/iancleary/ansible-role-zsh
  name: iancleary.zsh_antibody
  version: v0.5.0
