  - name: Clone dotfiles
    git:
      repo: https://github.com/justin-p/dotfiles.git
      dest: "{{ ansible_env.HOME }}/.dotfiles"

  - name: Clone fzf
    git:
      repo: https://github.com/junegunn/fzf
      dest: "{{ ansible_env.HOME }}/.fzf/"
      depth: 1

  - name: Clone tmux plugin manager
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
      depth: 1

  - name: Clone vim-airline
    git:
      repo: https://github.com/vim-airline/vim-airline
      dest: "{{ ansible_env.HOME }}/.vim/pack/dist/start/vim-airline"
      depth: 1

  - name: Clone vim-airline-themes
    git:
      repo: https://github.com/vim-airline/vim-airline-themes
      dest: "{{ ansible_env.HOME }}/.vim/pack/dist/start/vim-airline-themes"
      depth: 1

  - name: Clone vim-airline
    git:
      repo: https://github.com/scopatz/nanorc
      dest: "{{ ansible_env.HOME }}/.nano"
      version: v2.9

  - name: Install stow
    apt:
      name:
        - stow
    become: yes

  - name: Remove .vimrc
    file:
      path: "{{ ansible_env.HOME }}/.vimrc"
      state: absent

  - name: Stow configurations
    command:
      chdir: "{{ ansible_env.HOME }}/.dotfiles"
      cmd: "stow {{ item }}"
    with_items:
    - bash
    - BurpSuite
    - flameshot
    - fzf
    - git
    - htop
    - hyper
    - nano
    - tmux
    - ulauncher
    - vim
    - zsh

  - name: Change user shell to zsh
    user:
      name: "{{ username }}"
      shell: /bin/zsh
    become: yes